version: "3.9"

services:
  gateway:
    build:
      context: ../..
      dockerfile: deploy/docker/Dockerfile
    ports:
      - "8080:8080"    # Proxy
      - "9090:9090"    # Admin / metrics
    volumes:
      - ../../configs/gateway.yaml:/configs/gateway.yaml:ro
    environment:
      - TZ=UTC
    depends_on:
      - redis
      - backend-a
      - backend-b
    restart: unless-stopped
    networks:
      - gw

  # Toy echo backend A
  backend-a:
    image: ealen/echo-server:latest
    environment:
      - PORT=3000
    networks:
      - gw

  # Toy echo backend B
  backend-b:
    image: ealen/echo-server:latest
    environment:
      - PORT=3000
    networks:
      - gw

  redis:
    image: redis:7-alpine
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    networks:
      - gw

  prometheus:
    image: prom/prometheus:v2.51.0
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9091:9090"
    networks:
      - gw

  grafana:
    image: grafana/grafana:10.4.0
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
    depends_on:
      - prometheus
    networks:
      - gw

networks:
  gw:
    driver: bridge
